### ISSUE TITLE
Having problems running test file

### ISSUE THREAD

**Issue by Yugler** [WISDEM/DriveSE#15]
Greetings,

I have followed install instructions in "https://github.com/WISDEM/WISDEM" and I'm able to run some other module examples like CCBlade but is not the case with DRiveSe.

When I run "test_DriveSE.py" i get following error: No module named "drivese.drive". Maybe is pointing to older modules?

Thanks for the help

**Comment by gnscott** [comment]
You are correct: test_DriveSE.py is old code that uses some modules and classes that don't exist any more. We'll replace it with something that works. In the meantime, assume that everything is working and try out DriveSE with your own code.
Thanks for pointing out the problem.
